
server:
  port: 8888


#Mybatis????
# ???????
#??mysql???(?????)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fzu?serverTimezone=GMT%2b8
    username: root
    password: 123456
  #  redis??
  redis:
    host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
    port: 6379
    password: Redis000


# ????Mapper.xml??
mybatis:
  mapper-locations: classpath:mapper/*.xml    #??xml??
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

